version: "3"

services:

  api:
    image: node:${NODE_VERSION}
    networks:
      - new_way_recruiter_network
    depends_on: 
      - db
    ports:
      - 3333:${NODE_PORT}
    command: yarn start:dev
    working_dir: ${WORKING_DIR}
    volumes:
      - ./api:/app
    env_file: ./api/.env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  new-way-recruiter-web:
    image: node:${NODE_VERSION}
    networks:
      - new_way_recruiter_network
    ports:
      - 3000:3000
    depends_on:
      - api
    command: yarn start
    working_dir: ${WORKING_DIR}
    stdin_open: true
    volumes:
      - ./new-way-recruiter-web:${WORKING_DIR}
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    networks:
      - new_way_recruiter_network
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "root"
  
  db:
    image: mysql
    networks:
      - new_way_recruiter_network
    ports:
      - "3306:3306"
    volumes:
      - mysqlDb:/var/lib/mysql
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newwayrec

networks:
  new_way_recruiter_network:

volumes:
  mysqlDb: