version: "3"

services:

  api:
    image: node:${NODE_VERSION}
    networks:
      - new_way_recruiter_network
    depends_on: 
      - datab
    ports:
      - 3333:${NODE_PORT}
    command: yarn start:dev
    working_dir: ${WORKING_DIR}
    volumes:
      - ./api:/app
    env_file: ./api/.env

  new-way-recruiter-web:
    image: node:${NODE_VERSION}
    networks:
      - new_way_recruiter_network
    ports:
      - 3000:3000
    depends_on:
      - api
    command: yarn start
    working_dir: ${WORKING_DIR}
    stdin_open: true
    volumes:
      - ./new-way-recruiter-web:${WORKING_DIR}
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    networks:
      - new_way_recruiter_network
    depends_on:
      - datab
    environment:
      PMA_HOST: datab
      MYSQL_ROOT_PASSWORD: root
  
  datab:
    image: mariadb:10
    networks:
      - new_way_recruiter_network
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: new
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newwayrec
      MYSQL_PASSWORD: root

networks:
  new_way_recruiter_network:

volumes:
  db_data: